import {ModelRegistry} from "./core/registry.mjs";
import {CapabilityRouter} from "./core/router.mjs";
import {RoutingPolicy} from "./core/policy.mjs";
import {CircuitBreaker} from "./core/circuit-breaker.mjs";
import {UsageLedger} from "./core/usage-ledger.mjs";
import {AgentGraph} from "./core/agent-graph.mjs";
import {MCPGateway} from "./mcp/gateway.mjs";
import {MCPAggregator} from "./mcp/aggregator.mjs";
import {MCPLifecycle} from "./mcp/lifecycle.mjs";
import {PluginRegistry} from "./plugins/registry.mjs";
import {SkillLoader} from "./skills/loader.mjs";
import {CredentialPool} from "./credentials/key-pool.mjs";
import {Planner} from "./agents/planner.mjs";
import {ConnectionManager} from "./auth/connection-manager.mjs";
import {AdaptiveScheduler} from "./core/adaptive-scheduler.mjs";
import {ContextCache} from "./core/context-cache.mjs";
import {EventBus} from "./observability/events.mjs";
import {ComplianceGate} from "./engagement/compliance-gate.mjs";
import {AudienceEngine} from "./engagement/audience.mjs";
import {TemplateRegistry} from "./engagement/template-registry.mjs";
import {CampaignEngine} from "./engagement/campaign-engine.mjs";
import {AutomationEngine} from "./engagement/automation-engine.mjs";
import {EngagementAnalytics} from "./engagement/analytics.mjs";
import {OmnichannelRouter} from "./engagement/omnichannel-router.mjs";
import {AuditLog} from "./engagement/audit-log.mjs";
import {DeliveryGovernor} from "./engagement/delivery-governor.mjs";
import {ExperimentEngine} from "./engagement/experiment-engine.mjs";
import {LeadScoring} from "./engagement/lead-scoring.mjs";
import {IdempotencyStore} from "./engagement/idempotency.mjs";
import {InboxEngine} from "./engagement/inbox-engine.mjs";
import {FrequencyCap} from "./engagement/frequency-cap.mjs";
import {CampaignPlanner} from "./engagement/campaign-planner.mjs";
import {RevenueAttribution} from "./engagement/revenue-attribution.mjs";
import {SmartSendTime} from "./engagement/smart-send.mjs";
import {AutomationGraph} from "./engagement/automation-graph.mjs";
import {WebhookGateway} from "./integrations/webhook-gateway.mjs";
import {ConnectorRegistry} from "./integrations/connector-registry.mjs";
import {TenantRBAC} from "./security/tenant-rbac.mjs";
import {SecretVault} from "./security/secret-vault.mjs";
import {BudgetManager} from "./security/budget-manager.mjs";
import {DurableQueue} from "./queue/durable-queue.mjs";
import {ProviderHealth} from "./observability/provider-health.mjs";
import {KnowledgeBase} from "./ai/knowledge-base.mjs";
import {IntentRouter} from "./ai/intent-router.mjs";
import {ModelRouter} from "./ai/model-router.mjs";
import {BackupManager} from "./storage/backup-manager.mjs";

export function createRuntime(config={}){
 const registry=new ModelRegistry(); const policy=new RoutingPolicy(config.routing); const router=new CapabilityRouter(registry); router.policy=policy;
 const events=new EventBus(), audience=new AudienceEngine(), compliance=new ComplianceGate(config.compliance), templates=new TemplateRegistry();
 const runtime={registry,policy,router,usage:new UsageLedger(),graph:new AgentGraph(config.graph),mcp:new MCPGateway(),plugins:new PluginRegistry(),skills:new SkillLoader(),credentials:new CredentialPool(),events,audience,compliance,templates,audit:new AuditLog()};
 runtime.connections=(config.masterKey??process.env.APP_MASTER_KEY)?new ConnectionManager({masterKey:config.masterKey??process.env.APP_MASTER_KEY}):null;
 runtime.circuitBreaker=new CircuitBreaker(config.circuitBreaker); router.circuitBreaker=runtime.circuitBreaker;
 runtime.contextCache=new ContextCache(config.cache); runtime.scheduler=new AdaptiveScheduler({registry,policy,circuitBreaker:runtime.circuitBreaker});
 runtime.mcpLifecycle=new MCPLifecycle(runtime.mcp); runtime.mcpAggregator=new MCPAggregator(runtime.mcp); runtime.planner=new Planner(runtime.router);
 runtime.campaigns=new CampaignEngine({compliance,audience,templates,events}); runtime.automation=new AutomationEngine({events});
 runtime.analytics=new EngagementAnalytics(); runtime.channels=new OmnichannelRouter(); runtime.deliveryGovernor=new DeliveryGovernor(config.delivery);
 runtime.experiments=new ExperimentEngine(); runtime.leadScoring=new LeadScoring(); runtime.idempotency=new IdempotencyStore();
 runtime.inbox=new InboxEngine({events}); runtime.frequencyCap=new FrequencyCap(config.frequency); runtime.campaignPlanner=new CampaignPlanner({templates});
 runtime.revenue=new RevenueAttribution(); runtime.smartSend=new SmartSendTime(); runtime.automationGraph=new AutomationGraph({events});
 runtime.webhooks=new WebhookGateway({secret:config.webhookSecret??process.env.WEBHOOK_SECRET}); runtime.connectors=new ConnectorRegistry();
 runtime.rbac=new TenantRBAC(); runtime.secrets=new SecretVault(); runtime.budgets=new BudgetManager(); runtime.queue=new DurableQueue(config.queue);
 runtime.providerHealth=new ProviderHealth(config.providerHealth); runtime.knowledgeBase=new KnowledgeBase(); runtime.intent=new IntentRouter(); runtime.models=new ModelRouter(); runtime.backups=new BackupManager();
 events.on("campaign.sent",e=>runtime.analytics.track?.("sent",e.contactId)); events.on("campaign.delivered",e=>runtime.analytics.track?.("delivered",e.contactId)); events.on("campaign.read",e=>runtime.analytics.track?.("read",e.contactId)); events.on("campaign.replied",e=>runtime.analytics.track?.("replied",e.contactId));
 return runtime;
}