const state={models:[],connections:[],providers:{},messages:JSON.parse(localStorage.getItem('creazzy.chat')||'[]'),token:localStorage.getItem('creazzy.token')||'',activity:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function headers(){return state.token?{'Authorization':'Bearer '+state.token,'Content-Type':'application/json'}:{'Content-Type':'application/json'};}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...headers(),...(opts.headers||{})}});let data={};try{data=await r.json()}catch{}if(!r.ok)throw Object.assign(new Error(data?.error?.message||data?.error||`HTTP ${r.status}`),{code:data?.error?.code,status:r.status});return data;}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2800);}
function renderStats(){const providers=new Set(state.models.map(x=>x.owned_by));$('#providers').textContent=providers.size;$('#models').textContent=state.models.length;$('#accounts').textContent=state.connections.length;$('#status').textContent='online';$('#connectionDot').classList.add('ok');$('#connectionText').textContent='Worker connected';}
function renderModels(){const list=$('#modelList');const select=$('#modelSelect');select.innerHTML='<option value="">Auto-route model</option>'+state.models.map(m=>`<option value="${esc(m.id)}">${esc(m.id)} · ${esc(m.owned_by)}</option>`).join('');list.innerHTML=state.models.length?state.models.map(m=>`<div class="model-row"><div><b>${esc(m.id)}</b><span>${esc(m.owned_by)}</span></div><span class="badge">available</span></div>`).join(''):'<div class="empty"><b>No models discovered</b><span>Add provider Worker Secrets and press Sync providers.</span></div>';}
function renderProviders(){const names=['deepseek','openai','nvidia','xai','google'];$('#providerGrid').innerHTML=names.map(p=>{const rows=state.connections.filter(x=>x.provider===p);const models=state.models.filter(x=>x.owned_by===p);return `<article class="provider-card"><div class="provider-head"><div class="provider-icon">${p[0].toUpperCase()}</div><div><h3>${esc(p)}</h3><span>${rows.length} account(s) · ${models.length} model(s)</span></div></div><div class="provider-meta"><span class="badge ${rows.length?'good':''}">${rows.length?'configured':'not configured'}</span><button class="button small" data-sync="${p}">Sync</button></div>${rows.length?'<div class="account-list">'+rows.map(x=>`<div><span>${esc(x.label||x.id)}</span><span class="status ${x.status}">${esc(x.status)}</span></div>`).join('')+'</div>':'<p class="muted">Add the provider secret in Cloudflare → Worker → Settings → Variables and Secrets.</p>'}</article>`}).join('');$$('[data-sync]').forEach(b=>b.onclick=()=>syncProvider(b.dataset.sync));}
function renderMini(){const names=['deepseek','openai','nvidia','xai','google'];$('#providerMini').innerHTML=names.map(p=>{const n=state.connections.filter(x=>x.provider===p).length;return `<div class="mini-row"><span><i class="dot ${n?'ok':''}"></i>${p}</span><b>${n} account${n===1?'':'s'}</b></div>`}).join('');}
function renderSystem(health){$('#healthDetails').innerHTML=[['Status',health.status||'unknown'],['Runtime',health.runtime||'unknown'],['Full stack',String(health.fullStack)],['Models',String(state.models.length)],['Accounts',String(state.connections.length)]].map(x=>`<div><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');$('#accessDetails').innerHTML=[['Browser token',state.token?'configured':'not set'],['Provider secrets','server-side'],['Routing','automatic failover'],['Account cap','10 / provider']].map(x=>`<div><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');$('#activity').innerHTML=state.activity.length?state.activity.slice(-20).reverse().map(x=>`<div class="activity-row"><span>${esc(x.time)}</span><b>${esc(x.message)}</b></div>`).join(''):'<div class="muted">No activity yet.</div>';}
function renderChat(){const box=$('#messages');box.innerHTML=state.messages.length?state.messages.map(m=>`<div class="msg ${m.role}"><span class="msg-role">${m.role==='user'?'YOU':'CREAZZY'}</span><div>${esc(m.content).replace(/\n/g,'<br>')}</div>${m.model?`<small>${esc(m.model)}</small>`:''}</div>`).join(''):'<div class="empty"><b>Ready.</b><span>Configure a provider secret, choose a model or let Creazzy route automatically.</span></div>';box.scrollTop=box.scrollHeight;}
async function load(){try{const [health,models,connections]=await Promise.all([api('/healthz'),api('/v1/models'),api('/connections')]);state.models=models.data||[];state.connections=connections.connections||[];renderStats();renderModels();renderProviders();renderMini();renderSystem(health);state.activity.unshift({time:new Date().toLocaleTimeString(),message:`Loaded ${state.models.length} models across ${new Set(state.models.map(x=>x.owned_by)).size} providers`});renderSystem(health);}catch(e){$('#status').textContent='error';$('#connectionText').textContent=e.code==='UNAUTHORIZED'?'API token required':'Runtime error';$('#connectionDot').classList.remove('ok');toast(e.message);}}
async function syncProvider(provider){try{const result=await api(`/providers/${encodeURIComponent(provider)}/sync`,{method:'POST'});toast(`${provider}: discovered ${result.count} model(s)`);await load();}catch(e){toast(`${provider}: ${e.message}`);}}
async function sendChat(e){e.preventDefault();const prompt=$('#prompt').value.trim();if(!prompt)return;const model=$('#modelSelect').value;state.messages.push({role:'user',content:prompt});saveChat();renderChat();$('#prompt').value='';const pending={role:'assistant',content:'Thinking…',model:''};state.messages.push(pending);renderChat();try{const payload={messages:state.messages.filter(m=>m.role!=='assistant'||m.content!=='Thinking…').map(m=>({role:m.role,content:m.content})),maxAttempts:4};if(model)payload.model=model;const result=await api('/v1/chat/completions',{method:'POST',body:JSON.stringify(payload)});pending.content=result?.choices?.[0]?.message?.content||JSON.stringify(result);pending.model=result?.model||model||'auto-routed';state.activity.unshift({time:new Date().toLocaleTimeString(),message:`Completed request with ${pending.model}`});saveChat();renderChat();renderSystem({status:'ok',runtime:'cloudflare-workers',fullStack:true});}catch(err){pending.content=`Request failed: ${err.message}`;pending.model=err.code||'error';state.activity.unshift({time:new Date().toLocaleTimeString(),message:`Request failed: ${err.code||err.message}`});saveChat();renderChat();toast(err.message);}}
function saveChat(){localStorage.setItem('creazzy.chat',JSON.stringify(state.messages.slice(-40)));}
function navigate(view){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${view}`));$('#viewTitle').textContent={chat:'Chat workspace',providers:'Providers & accounts',models:'Model registry',system:'Runtime & health'}[view];}
$$('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.view));$('#chatForm').onsubmit=sendChat;$('#refreshAll').onclick=load;$('#syncModels').onclick=async()=>{for(const p of ['deepseek','openai','nvidia','xai','google'])try{await syncProvider(p)}catch{}};
$('#clearChat').onclick=()=>{state.messages=[];saveChat();renderChat();};$('#settingsButton').onclick=()=>{$('#apiToken').value=state.token;$('#accessModal').classList.remove('hidden')};$('#closeModal').onclick=()=>$('#accessModal').classList.add('hidden');$('#saveToken').onclick=()=>{state.token=$('#apiToken').value.trim();state.token?localStorage.setItem('creazzy.token',state.token):localStorage.removeItem('creazzy.token');$('#accessModal').classList.add('hidden');load();};$('#removeToken').onclick=()=>{state.token='';localStorage.removeItem('creazzy.token');$('#apiToken').value='';load();};
renderChat();load();