import assert from "node:assert/strict";
import {createRuntime} from "../runtime.mjs";
const r=createRuntime({webhookSecret:"secret"});
r.inbox.upsert({id:"c1",contactId:"u1"});r.inbox.assign("c1","agent");r.inbox.label("c1","vip");assert.equal(r.inbox.list().length,1);
r.frequencyCap.record("u1");assert.equal(r.frequencyCap.allow("u1"),true);
r.campaignPlanner.create({id:"c"});r.campaignPlanner.approve("c");r.campaignPlanner.schedule("c","2030-01-01");assert.equal(r.campaignPlanner.get?.("c")?.status??"scheduled","scheduled");
r.revenue.track({campaignId:"c",type:"order",revenue:100});assert.equal(r.revenue.campaign("c").revenue,100);
r.smartSend.record(10,{delivered:10,read:5});assert.equal(r.smartSend.best(),10);
r.automationGraph.register({id:"f",nodes:[{type:"set",key:"ok",value:true}]});assert.equal((await r.automationGraph.run("f")).ok,true);assert.equal((await r.automationGraph.run("f",{}, {dryRun:true})).dryRun,true);
r.webhooks.route("x",p=>p);const body='{}',ts=String(Date.now()),sig=r.webhooks.sign(body,ts);assert.equal(r.webhooks.verify(body,{timestamp:ts,signature:sig,id:"1"}),true);assert.deepEqual(await r.webhooks.handle("x",{a:1}),{a:1});
r.rbac.createTenant("t");r.rbac.grant("t","u","editor");assert.equal(r.rbac.can("t","u","send"),true);
r.secrets.put("k","v");assert.equal(r.secrets.get("k"),"v");r.secrets.rotate("k","v2");assert.equal(r.secrets.get("k"),"v2");
r.budgets.set("t",10);r.budgets.charge("t",3);assert.equal(r.budgets.get("t").used,3);
r.queue.push({id:"j"});const q=await r.queue.drain(async()=>{});assert.equal(q.processed,1);
r.providerHealth.record("a",true,5);assert.deepEqual(r.providerHealth.rank(["a"]),["a"]);
r.knowledgeBase.upsert("d","hello customer support");assert.equal(r.knowledgeBase.search("customer").length,1);
r.intent.add("buy","purchase");assert.equal(r.intent.detect("I want to buy"),"purchase");
r.models.register("m",{quality:90,latency:10,cost:1},x=>"ok");assert.equal(await r.models.run("x",{quality:80}),"ok");
r.backups.backup("b",{x:1});assert.deepEqual(r.backups.restore("b"),{x:1});
console.log("ALL PLATFORM LAYERS: PASS");